global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  
  - job_name: 'redis'
    metrics_path: /
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['redis:6379']
  # - job_name: 'docker'
  #   static_configs:
  #     - targets: ['docker-socket-proxy:2375']

